<a href="https://colab.research.google.com/github/Putthakun/EDA/blob/main/SVM_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Handle the given data with EDA techniques

## Import Python Libraies

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm, datasets
from sklearn.metrics import f1_score
import sklearn.model_selection as model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

## read data

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data/loan approval.csv")

## Clean data

In [ ]:
data["Status"] = data["Status"].replace("N", 0).replace("Y", 1)

In [ ]:
data["Income(dollar)"] = round(data["Income(dollar)"], 2)

In [ ]:
data["Loan_Amount"] = round(data["Loan_Amount"], 2)

In [ ]:
data['loan_History'] = data['loan_History'].fillna(data['loan_History'].median())

In [ ]:
data.dropna()

,Gender,Married,Dependents,Education,Self_Employed,Income(dollar),Coapplicant,Loan_Amount,Term(month),loan_History,Area,Status
0,Male,No,0,Not Graduate,No,144200.0,No,3500000,360.0,1.0,Urban,0
1,Female,No,3+,Not Graduate,No,183000.0,No,0,360.0,0.0,Urban,0
2,Male,Yes,1,Graduate,No,188000.0,No,6100000,360.0,1.0,Rural,0
3,Male,Yes,0,Graduate,No,195000.0,Yes,13500000,360.0,1.0,Rural,0
4,Female,No,0,Not Graduate,No,196300.0,No,5300000,360.0,1.0,Semiurban,1
...,...,...,...,...,...,...,...,...,...,...,...,...
606,Male,No,0,Graduate,No,3567300.0,Yes,9000000,360.0,1.0,Urban,0
607,Male,No,1,Graduate,No,3771900.0,No,15200000,360.0,1.0,Semiurban,1
608,Male,Yes,3+,Graduate,No,3999900.0,No,60000000,180.0,0.0,Semiurban,1
610,Male,Yes,0,Graduate,Yes,4389700.0,Yes,12000000,360.0,1.0,Semiurban,1
613,Male,Yes,3+,Graduate,No,8100000.0,No,36000000,360.0,0.0,Rural,0

## SVM model

In [ ]:
x = data[['Income(dollar)','Loan_Amount','loan_History']]
y = data['Status']

In [ ]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, train_size=0.80, test_size=0.20, random_state=101)

In [ ]:
linear = svm.SVC(kernel='linear', C=0.1)
linear.fit(X_train, y_train)

rbf = svm.SVC(kernel='rbf', gamma=0.5, C=0.1)
rbf.fit(X_train, y_train)

poly = svm.SVC(kernel='poly', degree=3, C=1)
poly.fit(X_train, y_train)

In [ ]:
poly_pred = poly.predict(X_test)
rbf_pred = rbf.predict(X_test)
linear_pred = linear.predict(X_test)

In [ ]:
poly_accuracy = accuracy_score(y_test, poly_pred)
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))

rbf_accuracy = accuracy_score(y_test, rbf_pred)
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*100))

linear_accuracy = accuracy_score(y_test, linear_pred)
print('Accuracy (Linear Kernel): ', "%.2f" % (linear_accuracy*100))